### ISSUE TITLE
GDPR Template Update

### ISSUE THREAD

**Issue by ix-certification** [indexexchange/optimera-adapter#3]
Hello,

We have updated our templates to incorporate the upcoming GDPR changes along with a few update/bug fixes. Please rebase your current code to the latest master-v2 branch. 

In addition, inside the mockPartnerConfig.json, please do not change the key names inside the "mapping" object. i.e. "728x90_970x250"

For more information regarding rebasing, please refer to https://help.github.com/articles/about-git-rebase/

Thanks,
IX

**Comment by mcallari** [comment]
Hello @ix-certification,

I have rebased, but getting some errors.

Namely:
"TypeError: Cannot read property 'gdpr' of undefined"

I can add the following to space-camp.js:
``` 
ComplianceService: {
  gdpr: {
    getConsent: function () {
      return {
         applies: true,
         consentString: 'stubbed-consent'
      };
   }
},
   isPrivacyEnabled: function () {
     return true;
 }
}
```
but is this correct? Also, is the master-v2 branch the latest stable version?

Thank you,
Mike

**Comment by mcallari** [comment]
@ix-certification I have rebased and added the ComplianceService. Let me know if this is ok now when you can. Thank you.

**Comment by ix-certification** [comment]
@mcallari We can see that the ComplianceService was added, however, the consent information from this service is not being used by the adapter in any way, is that expected?

**Comment by mcallari** [comment]
@ix-certification Right, the test suite wouldn't run without it, so that's why I had to add it.

**Comment by ix-certification** [comment]
This ComplianceService was added to ensure that all the partners in the IX wrapper have access to the consent information being provided by a CMP of Publisher's choice. 

If Optimera is not subject to GDPR regulations, then this consent information doesn't need to be consumed and we can leave things as they are.

**Comment by mcallari** [comment]
@ix-certification Ok perfect. Optimerai is not subject to GDPR. Thank you much.
