### ISSUE TITLE
Removing divID as an XSlot Config

### ISSUE THREAD

**Issue by ix-certification** [indexexchange/optimera-adapter#6]
If divID is not needed to be configured upfront, then we should update following line  

https://github.com/indexexchange/optimera-adapter/blob/5a0a4f38e3604f0ff4d5d098be82ffb344438f67/optimera-htb.js#L328

to instead use `var divID = curReturnParcel.ref.getSlotElementId()`. Additionally, we should remove the ref of divID as xslot configs in other files as well.

**Comment by mcallari** [comment]
@ix-certification: ref is empty on the xSlotRef when running the tests, therefore getSlotElementId() is not available and the tests obviously fail. Is there something else I need to do get the slot element id?
